Oriana/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

class User(models.Model):

    username = models.CharField(max_length=200)

    ## Authentication Statistics
    succ_auth_events = models.IntegerField(default=0)
    failed_auth_events = models.IntegerField(default=0)

    unique_succ_local_hosts = models.IntegerField(default=0)
    unique_succ_remote_hosts= models.IntegerField(default=0)

    unique_failed_remote_hosts = models.IntegerField(default=0)

    unique_succ_rdp_hosts = models.IntegerField(default=0)
    unique_succ_network_hosts = models.IntegerField(default=0)

    def __str__(self):
        return self.username

class Host(models.Model):

    hostname = models.CharField(max_length=200)

    ## Host Statistics
    total_succ_auths = models.IntegerField(default=0)
    total_failed_auths = models.IntegerField(default=0)

    unique_succ_remote_users = models.IntegerField(default=0)
    unique_succ_local_users = models.IntegerField(default=0)

    unique_failed_remote_users = models.IntegerField(default=0)
    unique_failed_local_users = models.IntegerField(default=0)

    def __str__(self):
        return self.hostname

class SourceIp(models.Model):

    #sourceip = models.GenericIPAddressField(blank=True,null=True)
    sourceip = models.CharField(max_length=100, blank=True)
    hostname = models.CharField(max_length=100, blank=True)

    total_succ_auths = models.IntegerField(default=0)
    total_failed_auths=models.IntegerField(default=0)

    unique_succ_remote_hosts = models.IntegerField(default=0)
    unique_failed_remote_hosts = models.IntegerField(default=0)

    def __str__(self):
        return str(self.sourceip) + ":"+str(self.hostname)

class Service(models.Model):

    servicename = models.CharField(max_length=1000)
    imagepath = models.CharField(max_length=10000)
    servicetype = models.CharField(max_length=30)

    count = models.IntegerField(default=0)
    ngramscore = models.IntegerField(default=0)

    def __str__(self):
        return self.servicename

class Task(models.Model):

    taskname = models.CharField(max_length=1000)
    imagepath = models.CharField(max_length=10000)
    arguments = models.CharField(max_length=10000)

    count = models.IntegerField(default=0)
    ngramscore = models.IntegerField(default=0)

    def __str__(self):
        return self.taskname

class FA_imagepath(models.Model):

    imagepath = models.CharField(max_length=10000)
    count = models.IntegerField(default=0)
    characterscount = models.IntegerField(default=0)


class Event_4624(models.Model):

    time= models.DateTimeField()
    host= models.ForeignKey(Host, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    domain = models.CharField(max_length=200)
    logontype = models.CharField(max_length=200)
    sourcehost = models.CharField(max_length=200)
    processname = models.CharField(max_length=5000)
    status = models.CharField(max_length=200)

    #sourceip = models.CharField(max_length=200)
    sourceip = models.ForeignKey(SourceIp,null=True)

class Event_4625(models.Model):

    time= models.DateTimeField()
    host= models.ForeignKey(Host, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    domain = models.CharField(max_length=200)
    logontype = models.CharField(max_length=200)
    sourcehost = models.CharField(max_length=200)
    processname = models.CharField(max_length=5000)

    status = models.CharField(max_length=200)
    substatus = models.CharField(max_length=200)

    #sourceip = models.CharField(max_length=200)
    sourceip = models.ForeignKey(SourceIp, null=True)

class Event_4776(models.Model):

    time= models.DateTimeField()
    host= models.ForeignKey(Host, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    procname = models.CharField(max_length=500)
    status = models.CharField(max_length=200)

class Event_4672(models.Model):

    time= models.DateTimeField()
    host= models.ForeignKey(Host, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    privilegelist= models.CharField(max_length=1500)

class Event_4688(models.Model):

    time= models.DateTimeField()
    host= models.ForeignKey(Host, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=200)

class Event_7045(models.Model):

    time = models.DateTimeField()
    host = models.ForeignKey(Host, on_delete=models.CASCADE)
    service= models.ForeignKey(Service, on_delete=models.CASCADE)


    def __str__(self):
        return self.host.hostname + ":"+self.service.servicename

class Event_5140(models.Model):

    time = models.DateTimeField()
    host = models.ForeignKey(Host, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    sourceip = models.ForeignKey(SourceIp, null=True)
    sharename = models.CharField(max_length=100)

    def __str__(self):
        return self.sharename

class Event_4698(models.Model):

    time = models.DateTimeField()
    host = models.ForeignKey(Host, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.host) + ":"+str(self.task.taskname)

class WmiEvent_2(models.Model):

    time = models.DateTimeField()
    host = models.ForeignKey(Host, on_delete=models.CASCADE)
    operationid= models.CharField(max_length=100)
    operation = models.CharField(max_length=1000)

class PossibleLmSession(models.Model):

    start = models.DateTimeField()
    end= models.DateTimeField()
    delta= models.CharField(max_length=50,null=True)
    hosts= models.CharField(max_length=3,null=True)
    users= models.CharField(max_length=3,null=True)

    # list of users involved in the campaign
    # used services and image paths
    # show unique services and binaries used
    # need to know what the source is

class PossibleLM(models.Model):


    auth= models.ForeignKey(Event_4624, on_delete=models.CASCADE)
    event_7045 = models.ForeignKey(Event_7045, on_delete=models.CASCADE, null=True)
    event_4698 = models.ForeignKey(Event_4698, on_delete=models.CASCADE, null=True)
    event_wmi_2 = models.ForeignKey(WmiEvent_2, on_delete=models.CASCADE, null=True)
    reason = models.CharField(max_length=200)

    attack_progression= models.ForeignKey(PossibleLmSession, related_name='attacks', on_delete=models.CASCADE, null=True, default=None)

class SuspiciousUserBehavior(models.Model):

    name = models.CharField(max_length=200)
    description= models.CharField(max_length=2000)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    start = models.DateTimeField()
    end = models.DateTimeField()

class SuspiciousSourceBehavior(models.Model):

    name = models.CharField(max_length=200)
    description= models.CharField(max_length=2000)
    source = models.ForeignKey(SourceIp, on_delete=models.CASCADE)
    start = models.DateTimeField()
    end = models.DateTimeField()

Oriana/templates/base2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block title %}Oriana - Hunt for Lateral Movement{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="/static/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/starter-template.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="/static/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="/static/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <!--<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>-->
      <!--<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>-->
      <script src="/static/js/html5shiv.min.js"></script>
      <script src="/static/js/respond.min.js"></script>
    <![endif]-->



  </head>

  <body>

  <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Oriana</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/dashboard/">Dashboard</a></li>
           <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Entities<span class="caret"></span></a>
              <ul class="dropdown-menu">
              <li><a href="/users/">Users</a></li>
              <li><a href="/hosts/">Hosts</a></li>
              <li><a href="/shosts/">Source Hosts</a></li>
              <li><a href="/services/">Services</a></li>
              <li><a href="/tasks/">Scheduled Tasks</a></li>
              <li role="separator" class="divider"></li>
              <li class="dropdown-header">Extracted Entities</li>
              <li><a href="/fa_cmdline/">Cmdline</a></li>
              </ul>
          </li>
             <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Suspicious<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="/suspicious_user_behavior/">Suspicious User Behavior</a></li>
                  <li><a href="/suspicious_source_behavior/">Suspicious Source Behavior</a></li>
                  <li><a href="/possible_lm/">Possible Lateral Movement Events</a></li>
                  <li><a href="/lm_sessions/">Possible Lateral Movement Sessions</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="/suspicious_behavior/">Suspicious Behavior</a></li>

                </ul>
              </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


    <div class="container">
    {% block content %}{% endblock %}
    </div><!-- /.container -->

  </body>
</html>

Oriana/templates/fa_cmdline.html
{% extends "base2.html" %}

{% block title %}Command Line{% endblock %}

{% block content %}
		<link rel="stylesheet" type="text/css" href="/static/css/datatables.min.css"/>
		<script type="text/javascript" src="/static/js/datatables.min.js"></script>
		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				$('#example').DataTable();
			} );
		</script>
  <h2>Command Line</h2>
  <p></p>
  <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>Id</th>
        <th>Cmdline</th>
        <th>Count</th>
        <th># of Characters</th>
      </tr>
    </thead>
    <tbody>
        {% for c in cmdlines %}
        <tr>


        <td><a href="/fa_cmdline/{{c.id}}">{{c.id}}</a></td>
        <td style="word-wrap: break-word;min-width: 160px;max-width: 300px;">{{ c.imagepath|truncatechars:255}}</td>
        <td>{{ c.count}}</td>
        <td>{{ c.characterscount}}</td>
        </tr>
        {% endfor %}

    </tbody>
  </table>
{% endblock %}

Oriana/templates/hosts.html
{% extends "base2.html" %}

{% block title %}Hosts{% endblock %}

{% block content %}

        <link rel="stylesheet" type="text/css" href="/static/css/datatables.min.css"/>
		<script type="text/javascript" src="/static/js/datatables.min.js"></script>

		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				$('#example').DataTable();
			} );
		</script>
  <h2>Hosts</h2>
  <p></p>
  <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>Id</th>
        <th>Hostname</th>
        <th>Succesfull Auth Events</th>
        <th>Failed Auth Events</th>
        <th># Unique Remote Users</th>
        <th>#Unique Local Users</th>
      </tr>
    </thead>
    <tbody>

        {% for host in hosts %}
        <tr>
        <td><a href="/host/{{host.id}}">{{host.id}}</a></td>
        <td>{{ host.hostname }}</td>
        <td>{{ host.total_succ_auths}}</td>
        <td>{{ host.total_failed_auths}}</td>
        <td>{{ host.unique_succ_remote_users}}</td>
        <td>{{ host.unique_succ_local_users}}</td>
        </tr>
        {% endfor %}

    </tbody>
  </table>
{% endblock %}

Oriana/templates/lm_sessions.html
{% extends "base2.html" %}

{% block title %}Possible Lateral Movement Events{% endblock %}

{% block content %}
        <link rel="stylesheet" type="text/css" href="/static/css/datatables.min.css"/>
		<script type="text/javascript" src="/static/js/datatables.min.js"></script>

		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				$('#example').DataTable();
			} );
		</script>
  <h2>{{progressions |length}} Possible Lateral Movement Sessions</h2>
  <p></p>
  <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>Id</th>
        <th>Start Time</th>
        <th>End Time</th>
        <th>Total Duration</th>
        <th>Uniquer Users</th>
        <th>Uniquer Hosts</th>
        <th># of Events</th>
      </tr>
    </thead>
    <tbody>
        {% for p in progressions %}
        <tr>
        <td><a href="/lmsession/{{p.id}}">{{p.id}}</a></td>
        <td>{{ p.start}}</td>
        <td>{{ p.end}}</td>
        <td>{{ p.delta}}</td>
        <td>{{ p.users}}</td>
        <td>{{ p.hosts}}</td>
        <td>{{ p.attacks.count}}</td>
        </tr>
        {% endfor %}

    </tbody>
  </table>
{% endblock %}

Oriana/templates/lmsession.html
{% extends "base.html" %}

{% block title %}Potential Lateral Movement Session #{% endblock %}

{% block content %}
<div class="row" >
    <h2>Lateral Movement Session #{{aprogression.id}}</h2>
    <dl class="dl-horizontal">
      <dt>Start Time</dt>
      <dd>{{ aprogression.start}}</a></dd>
      <dt>End Time</dt>
      <dd>{{ aprogression.end}}</a></dd>
      <dt>Duration</dt>
      <dd>{{ aprogression.delta}}</dd>
      <dt>Total Nomber of Hosts</dt>
      <dd>{{ aprogression.hosts}}</dd>
      <dt>Total Nomber of Users</dt>
      <dd>{{ aprogression.users}}</dd>
    </dl>
</div>
<div class="row">
    <!-- Bootstrap core CSS -->
    <link href="/static/css/timeline.css" rel="stylesheet">
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"> -->
    <link rel="stylesheet" href="/static/css/awesome.min.css">
        <div class="page-header">
        <h1 id="timeline">Timeline</h1>
    </div>

<div class="container-fluid">
        <div class="col-md-12">
            <div class="row">
                <div class="timeline">
                    {% for event in events %}
                    <span class="timeline-label">
                        <span class="label label-primary">{{event.auth.time|date:"N d, Y, h:i:s a" }}</span>
                    </span>
                    <div class="timeline-item timeline-item-{% cycle 'left' 'right' %}">
                        <div class="timeline-point timeline-point-blank"></div>
                        <div class="timeline-event timeline-event-default">
                            <div class="timeline-heading">
                                <h4>Victim: {{event.auth.host}}</h4>
                            </div>
                            <div class="timeline-body">
                                <p class="text-left">
                                     <dl class="dl-horizontal">
                                      <dt>Type</dt>
                                      {% if event.event_7045 %}
                                      <dd>Malicious Service </dd>
                                      {% elif event.event_4698 %}
                                      <dd>Malicious Task</dd>
                                      {% elif event.event_wmi_2 %}
                                      <dd>WMI Execution</dd>
                                      {% endif %}
                                      <dt>Username</dt>
                                      <dd>{{ event.auth.user}}</a></dd>
                                      <dt>Source Host</dt>
                                      <dd>{{ event.auth.sourcehost}}</a></dd>
                                      <dt>Source Ip</dt>
                                      <dd>{{ event.auth.sourceip}}</dd>
                                      {% if event.event_7045 %}
                                      <dt>Service Name</dt>
                                      <dd>{{ event.event_7045.service.servicename}}</dd>
                                      <dt>Cmdline</dt>
                                      <dd>{{ event.event_7045.service.imagepath}}</dd>
                                      {% elif event.event_4698 %}
                                      <dt>Task Name</dt>
                                      <dd>{{ event.event_4698.task.taskname}}</dd>
                                      <dt>Cmdline</dt>
                                      <dd>{{ event.event_4698.task.imagepath}}</dd>
                                      <dt>Arguments</dt>
                                      <dd>{{ event.event_4698.task.arguments}}</dd>
                                      {% endif %}



                                    </dl>
                                </p>
                            </div>
                            <div class="timeline-footer">
                                <p class="text-right"></p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <span class="timeline-label">
                        <button class="btn btn-danger"><i class="fa fa-ambulance"></i></button>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Oriana/templates/possible_lm_detail.html
{% extends "base.html" %}

{% block title %}Possible Lateral Movement{% endblock %}

{% block content %}
<div class="row" >
    <h3>Details</h3>
    <dl class="dl-horizontal">
      {% if event.event_7045 %}
      <dt>Victim</dt>
      <dd><a href="/host/{{ event.auth.host.id}}">{{ event.auth.host}}</a></dd>
      <dt>User</dt>
      <dd><a href="/user/{{ event.auth.user.id}}">{{ event.auth.user}}</a></dd>
      <dt>Command Line</dt>
      <dd >{{ event.event_7045.service.imagepath |truncatechars:200}}</dd>
      <dt>Source Ip</dt>
      <dd>{{ event.auth.sourceip}}</dd>
      <dt>Source Host</dt>
      <dd>{{ event.auth.sourcehost }}</dd>
      <dt>Type</dt>
      <dd>Service Creation</dd>
      {% elif event.event_4698 %}
      <dt>Victim</dt>
      <dd><a href="/host/{{ event.auth.host.id}}">{{ event.auth.host}}</a></dd>
      <dt>User</dt>
      <dd><a href="/user/{{ event.auth.user.id}}">{{ event.auth.user}}</a></dd>
      <dt>Command Line</dt>
      <dd>{{ event.event_4698.task.imagepath}}</dd>
      <dt>Arguments</dt>
      <dd>{{ event.event_4698.task.arguments}}</dd>
      <dt>Source Ip</dt>
      <dd>{{ event.auth.sourceip}}</dd>
      <dt>Source Host</dt>
      <dd>{{ event.auth.sourcehost }}</dd>
      <dt>Type</dt>
      <dd>Scheduled Task</dd>
      {% elif event.event_wmi_2 %}
      <dt>Victim</dt>
      <dd><a href="/host/{{ event.auth.host.id}}">{{ event.auth.host}}</a></dd>
      <dt>User</dt>
      <dd><a href="/user/{{ event.auth.user.id}}">{{ event.auth.user}}</a></dd>
      <dt>Command Line</dt>
      <dd>:(</dd>
      <dt>Source Ip</dt>
      <dd>{{ event.auth.sourceip}}</dd>
      <dt>Source Host</dt>
      <dd>{{ event.auth.sourcehost }}</dd>
      <dt>Type</dt>
      <dd>Wmi Execution</dd>
      {% endif %}
    </dl>
</div>
<div class="row" >
  <h4>Authentication Event</h4>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Time</th>
        <th>Username</th>
        <th>Host</th>
        <th>Source Workstation</th>
        <th>Source Ip</th>
        <th>Logon Type</th>
      </tr>
    </thead>
    <tbody>
        <tr>
        <td>{{ event.auth.time|date:"N d, Y, h:i:s a"}}</td>
        <td>{{ event.auth.user}}</td>
        <td>{{ event.auth.host}}</td>
        <td>{{ event.auth.sourcehost }}</td>
        <td>{{ event.auth.sourceip}}</td>
        <td>{{ event.auth.logontype}}</td>
        </tr>

    </tbody>
  </table>
</div>
<div class="row" >
  {% if event.event_7045 %}
  <h4>Service Creation Event</h4>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Time</th>
        <th>Host</th>
        <th>Service Name</th>
        <th>Image Path</th>
        <th>Service Type</th>
      </tr>
    </thead>
    <tbody>
        <tr>
        <td>{{ event.event_7045.time|date:"N. d, Y, h:i:s A"}}</td>
        <td>{{ event.event_7045.host}}</td>
        <td>{{ event.event_7045.service.servicename}}</td>
        <td style="word-wrap: break-word;min-width: 160px;max-width: 300px;">{{ event.event_7045.service.imagepath}}</td>
        <td>{{ event.event_7045.service.servicetype}}</td>
        </tr>

    </tbody>
  </table>
    {% endif %}
  {% if event.event_4698 %}
  <h4>Scheduled Task Event</h4>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Time</th>
        <th>Host</th>
        <th>Taskname</th>
        <th>Image Path</th>
        <th>Arguments</th>
      </tr>
    </thead>
    <tbody>
        <tr>
        <td>{{ event.event_4698.time|date:"N. d, Y, h:i:s A"}}</td>
        <td>{{ event.event_4698.host}}</td>
        <td>{{ event.event_4698.task.taskname}}</td>
        <td style="word-wrap: break-word;min-width: 160px;max-width: 160px;">{{ event.event_4698.task.imagepath}}</td>
        <td style="word-wrap: break-word;min-width: 160px;max-width: 160px;">{{ event.event_4698.task.arguments}}</td>
        </tr>

    </tbody>
  </table>
    {% endif %}

     {% if event.event_wmi_2 %}
  <h4>WMI Exec Event</h4>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Time</th>
        <th>Host</th>
        <th>WMI Operation Id</th>
        <th>WMI Operation</th>
      </tr>
    </thead>
    <tbody>
        <tr>
        <td>{{ event.event_wmi_2.time|date:"N. d, Y, h:i:s A"}}</td>
        <td>{{ event.event_wmi_2.host}}</td>
        <td>{{ event.event_wmi_2.operationid}}</td>
        <td>{{ event.event_wmi_2.operation}}</td>
        </tr>

    </tbody>
  </table>
    {% endif %}

</div>
{% endblock %}

Oriana/templates/service.html
{% extends "base.html" %}

{% block title %}{{ user.username}}'s Profile{% endblock %}

{% block content %}
<div class="row" >
    <h3>Details</h3>
    <dl class="dl-horizontal">
      <dt>Service Name</dt>
      <dd>{{ service.servicename}}</dd>
      <dt>Cmdline</dt>
      <dd>{{ service.imagepath}}</dd>
      <dt>Type</dt>
      <dd >{{ service.servicetype}}</dd>
      <dt>Unique Hosts</dt>
      <dd>{{ service.count}}</dd>
    </dl>
      <br>
         <div class="panel-group" id="accordion">
        <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">Service Creation Events</a>
        </h4>
      </div>
      <div id="collapse3" class="panel-collapse collapse">
        <div class="panel-body">
  <table id="remote_table" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>Time</th>
        <th>Hostname</th>
      </tr>
    </thead>
    <tbody>
        {% for event in events %}
        <tr>
        <td>{{ event.time|date:"N d, Y, h:i:s a" }}</td>
        <td>{{ event.host.hostname}}</td>

        </tr>
        {% endfor %}

    </tbody>
  </table>
        </div>
      </div>
    </div>

</div>

{% endblock %}

Oriana/templates/suspicious_source_behavior.html
{% extends "base2.html" %}

{% block title %}Suspicious Host Behavior{% endblock %}

{% block content %}

        <link rel="stylesheet" type="text/css" href="/static/css/datatables.min.css"/>
		<script type="text/javascript" src="/static/js/datatables.min.js"></script>

		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				$('#example').DataTable();
			} );
		</script>

  <h2>{{sources |length}} Hosts with Suspicious Behavior</h2>
  <p></p>
  <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>Id</th>
        <th>Hosts</th>
        <th>Total Duration</th>
        <th># of Leads</th>
      </tr>
    </thead>
    <tbody>
        {% for s in sources%}
        <tr>
        <td><a href="/shost/{{s.id}}">{{s.id}}</a></td>
        <td>{{ s.sourceip}}</td>
        <td>{{ s.suspicioussourcebehavior_set.all|length}}</td>
            <td><a href="/suspicious_source_behavior/{{s.id}}">{{ s.suspicioussourcebehavior_set.all|length}}</a></td>
        </tr>
        {% endfor %}

    </tbody>
  </table>
{% endblock %}

Oriana/templates/suspicious_user_behavior.html
{% extends "base2.html" %}

{% block title %}Suspicious User Behavior{% endblock %}

{% block content %}

        <link rel="stylesheet" type="text/css" href="/static/css/datatables.min.css"/>
		<script type="text/javascript" src="/static/js/datatables.min.js"></script>

		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				$('#example').DataTable();
			} );
		</script>

  <h2>{{users |length}} Users with Suspicious Behavior</h2>
  <p></p>
  <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>Id</th>
        <th>User</th>
        <th>Total Duration</th>
        <th># of Leads</th>
      </tr>
    </thead>
    <tbody>
        {% for u in users%}
        <tr>
        <td><a href="/user/{{u.id}}">{{u.id}}</a></td>
        <td>{{ u.username}}</td>
        <td>{{ u.suspicioususerbehavior_set.all|length}}</td>
            <td><a href="/suspicious_user_behavior/{{u.id}}">{{ u.suspicioususerbehavior_set.all|length}}</a></td>
        </tr>
        {% endfor %}

    </tbody>
  </table>
{% endblock %}